---
- hosts: all
  become: true
  pre_tasks:

  - name: install updates for centos
    ansible.builtin.dnf:
      update_cache: yes
      update_only: yes
    when: ansible_distribution == "CentOS"

  - name: install updates for ubuntu
    ansible.builtin.apt:
      update_cache: yes
      upgrade: dist
    when: ansible_distribution == "Ubuntu"

- hosts: web_server
  become: true
  tasks:
  
  - name: install apache2 on ubnutu
    ansible.builtin.apt:
      name:
        - apache2
        - libapache2-mod-php
          #  when: ansible_distribution == "Ubuntu"

- hosts: db_server
  become: true
  tasks:
  
  - name: install mariadb centos
    ansible.builtin.dnf:
      name: mariadb
      state: latest    
        #when: ansible_distribution == "CentOS"
